-- Create leaders table
CREATE TABLE leaders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position TEXT NOT NULL,
  department TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create schedules table
CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  time TIME NOT NULL,
  content TEXT NOT NULL,
  leader_id BIGINT REFERENCES leaders(id) ON DELETE CASCADE,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE leaders ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow all for anonymous for now, since there's no auth yet)
CREATE POLICY "Allow public read access on leaders" ON leaders FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on leaders" ON leaders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on leaders" ON leaders FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access on leaders" ON leaders FOR DELETE USING (true);

CREATE POLICY "Allow public read access on schedules" ON schedules FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on schedules" ON schedules FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on schedules" ON schedules FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access on schedules" ON schedules FOR DELETE USING (true);
